# Generated by Django 5.1.4 on 2024-12-30 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Masala', 'ML'), ('Doodh', 'DL'), ('Ginger', 'GL'), ('EL', 'Elaichi'), ('KIWI', 'KL'), ('LA', 'lattice')], max_length=7)),
            ],
        ),
    ]
