# Generated by Django 5.1.4 on 2024-12-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('ML', 'Masala'), ('DL', 'Doodh'), ('GL', 'Ginger'), ('EL', 'Elaichi'), ('KIWI', 'KL'), ('lattice', 'LA')], max_length=7),
        ),
    ]
