# Generated by Django 5.1.4 on 2024-12-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivarity_description_alter_chaivarity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('Masala', 'ML'), ('DL', 'Doodh'), ('GL', 'Ginger'), ('Elaichi', 'EL'), ('KIWI', 'KL'), ('LA', 'lattice')], max_length=7),
        ),
    ]
